---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: continuousdelivery-production
  namespace: production
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: continuousdelivery-production
  chart:
    git: git@github.com:MartinAhrer/continuousdelivery-gitops.git
    path: helm/
    ref: master
  values:
    image:
      repository: softwarecraftsmen/continuousdelivery-app
      tag: production-1-a098138
    replicaCount: 3
    ingress:
      hosts:
      - continuousdelivery-production.10.18.58.14.xip.io
    postgresql:
      initdbScriptsConfigMap: continuousdelivery-production