---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: continuousdelivery-development
  namespace: development
  annotations:
    flux.weave.works/tag.chart-image: glob:development-*
spec:
  releaseName: continuousdelivery-development
  chart:
    git: https://github.com/SoftwareCraftsmen/continuousdelivery.git
    path: src/main/helm
    ref: feature/issue-7-Add_kubernetes_manifest
  values:
    replicaCount: 1
    image:
      repository: softwarecraftsmen/continuousdelivery-app
      tag: development-bjkqfqve
    ingress:
      hosts:
      - continuousdelivery-development.10.18.58.14.xip.io
    postgresql:
      initdbScriptsConfigMap: continuousdelivery-development

