---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: continuousdelivery-development
  namespace: development
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:development-*
spec:
  releaseName: continuousdelivery-development
  chart:
    git: git@github.com:MartinAhrer/continuousdelivery-gitops.git
    path: helm/
    ref: master
  values:
    replicaCount: 1
    image:
      repository: softwarecraftsmen/continuousdelivery-app
      tag: development-bjkqfqve
    ingress:
      hosts:
      - continuousdelivery-development.10.18.58.14.xip.io
    postgresql:
      initdbScriptsConfigMap: continuousdelivery-development

